# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 04:23
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Card = apps.get_model('tasks', 'Card')
    Task = apps.get_model('tasks', 'Task')

    db_alias = schema_editor.connection.alias
    default_card = Card.objects.using(db_alias).create(name='default card')
    Task.objects.using(db_alias).filter(card=None).update(card=default_card)

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160729_0922'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
