# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20160802_0607'),
    ]

    operations = [
        # Thanx Postgre!
        migrations.RunSQL("""
            update tasks_task
            -- row_number() count from 1, but position starts from 0
            set position = with_position.newpos - 1
            from (
                select id, row_number() over (partition by card_id) as newpos
                from tasks_task
            ) as with_position
            where tasks_task.id = with_position.id
        """, migrations.RunSQL.noop)
    ]
