# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 00:12
from __future__ import unicode_literals

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20160802_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
