# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_card_position'),
    ]

    operations = [
        migrations.RunSQL("""
            update tasks_card
            -- row_number() count from 1, but position starts from 0
            set position = with_position.newpos - 1
            from (
                select id, row_number() over () as newpos
                from tasks_card
            ) as with_position
            where tasks_card.id = with_position.id
        """, migrations.RunSQL.noop)
    ]
